---
index: 0
logging:
  level: info
datadog_key:
  api_key: one_key
  application_key: another_key
mbus: nats://localhost:4222
intervals:
  discover: 60
  varz: 10
  healthz: 5
  local_metrics: 10
  prune: 300
  nats_ping: 10
